language: rust

rust:
- nightly

matrix:
  include:
    - os: linux
    - os: osx

addons:
  homebrew:
    packages:
    - binutils

cache:
  directories:
    - $HOME/.cargo
    - $HOME/.xargo
    - $TRAVIS_BUILD_DIR/target

before_script:
- rustup component add rust-src
- "(test -x $HOME/.cargo/bin/xargo || cargo install xargo)"

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

script:
- make objcopy
