cargo-features = ["publish-lockfile"]

[package]
name = "bootloader"
version = "0.2.0-beta"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
license = "MIT/Apache-2.0"
description = "An experimental pure-Rust x86 bootloader."
publish-lockfile = true

[dependencies]
xmas-elf = "0.6.2"
x86_64 = "0.2.7"
usize_conversions = "0.2.0"
os_bootinfo = "0.2.0"
fixedvec = "0.2.3"
spin = "0.4.8"
uart_16550 = { version = "0.1.0", optional = true }
lazy_static = { version = "1.0.2", features = ["spin_no_std"] }

[features]
serial = ["uart_16550"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = false
debug = true
